Updated samples for the Adobe PDF Services SDK 3.0.0
adobe/pdfservices-java-sdk-samples pull request #34
Opened 2022-09-23 08:30 UTC by vardhi

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-25 07:51 UTC, ankur010592 requested changes

2022-09-25 07:51 UTC, ankur010592 commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEGZip.java
> +            LOGGER.info("media type of the received asset is "+results.get(0).getMediaType());
What is the use case of adding a log line here?

2022-09-25 08:24 UTC, anubhav-mhjn requested changes

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdf/ExportPDFToDOCXWithOCROption.java
> +            //Set export pdf ocr option
Create a new ExportPDFOptions instance from the specified OCR locale and set it into the operation

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdf/ExportPDFToDOCXWithOCROption.java
> +            ExportPDFOperation exportPdfOperation = ExportPDFOperation.createNew(ExportPDFTargetFormat.DOCX);
variable name should be exportPDFOperation

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdf/ExportPDFToDOCXWithOCROption.java
> +            result.saveAs("output/exportPdfOutputWithOCR.docx");
exportPDFWithOCROptionsOutput.docx

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdf/ExportPDFToDOCXWithOCROption.java
> +
Please remove this extra line.

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEGZip.java
> +            // Execute the operation.
Let us either keep a full stop everywhere in the file comments, or remove it from everywhere in the file comments.

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/pdfproperties/GetPDFProperties.java
> +            // get properties of the pdf
Put an extraline before this comment.

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/pdfproperties/GetPDFProperties.java
> +            // Execute the operation pdf properties operation
Execute the operation

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/pdfproperties/GetPDFProperties.java
> +            // get properties of the pdf
Fetch the requisite properties of the specified PDF

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/pdfproperties/GetPDFProperties.java
> +            LOGGER.info("The Fonts used in the PDF: ");
Put an extra line before this log statement

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEGZip.java
> +            // Set the output type to create zip of images
Set the operation output type as Zip of images

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEGZip.java
> +            results.get(0).saveAs("output/exportPDFToJPEG.zip");
exportPDFToJPEGOutput.zip

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEGZip.java
> +            //to obtain the media type of asset
Is there any explicit reqt to keep this logging statement?

2022-09-25 08:24 UTC, anubhav-mhjn commented on src/main/java/com/adobe/pdfservices/operation/samples/exportpdftoimages/ExportPDFToJPEG.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ExportPDFToJPEG.class);
We can change the output naming for this class from exportPDFToImagesOutput_ to exportPDFToJPEGOutput_

2022-09-26 06:33 UTC, ankur010592 approved these changes

2022-09-26 06:56 UTC, anubhav-mhjn approved these changes

2022-09-26 09:39 UTC, pulkit-maheshwr approved these changes

2022-09-26 09:45 UTC, merged